networks:
  sse-network:
    external: true
    name: sse-network

services:
  odxt-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odxt-backend
    ports:
      - "8001:8001"
    environment:
      - REDIS_HOST=sse-redis
    networks:
      - sse-network
    restart: unless-stopped
